- sriov/sriov.go
Change-Id: Iadf5c8cd377592fe2529cf4ed63cdf91b8055176
> Resetting VLAN tag on VF interface deletion

- sriov/sriov.go
> Handing empty network ns

- sriov/sriov.go
This patch fixes the issue of VF naming/renaming inconsistencies where VFs share PF. With this fix VFs are sorted before selection by their index instead of solely relying on their names.
Change-Id: I4082abc8067f24e2554837575f80de5f26cf5765
> shared VF selection by link index

- sriov/sriov.go
Change-Id: I870bcbc636a8344a4c97ef21ac1c7545791fc09a
> adding dpdk mode vlan fix

- images/Dockerfile
- images/README.md
- images/build_docker.sh
- images/entrypoint.sh
- images/sriov-cni-daemonset.yaml
Adds a Docker image for distribution of sriov CNI
binary in a Docker image.
> [docker-image] Adds a Docker image for distribution

- .travis.yml
- README.md
Change-Id: Id0f7cf5154b79933a0496aec78346ef08861512f
> add basic .travis.yml

- sriov/main.go
After gain IPAM's ip in CMD ADD release it if error happens
Fixes #39
> Release IPAM's IP when error occurs

- sriov/sriov.go
> fix device lookup failure inside namespace

- README.md
Update README.md to mention that Mellanox cards are supported and
how to enable SR-IOV for Mellanox cards
> Add support to Mellanox cards

- Dockerfile
- Makefile
- images/entrypoint.sh
- images/sriov-cni-daemonset.yaml
This change also include following  related files changes as well:
Makefile
images/entrypoint.sh
images/sriov-cni-daemonset.yaml
> update docker file for alpine base image

- README.md
Adding go report card : https://goreportcard.com/report/github.com/intel/sriov-cni
> README.md: adding go report card

- images/k8s-v1.10-v1.15/sriov-cni-daemonset.yaml
- images/k8s-v1.16/sriov-cni-daemonset.yaml
With image imagePullPolicy set to IfNotPreset the user doesn't need to pull the image manually
> Change daemonset imagePullPolicy from Never to IfNotPreset

- images/k8s-v1.10-v1.15/sriov-cni-daemonset.yaml
- images/k8s-v1.16/sriov-cni-daemonset.yaml
> Use latest image version v2.3 in daemon templates

- Makefile
Makefile should be able to delete everything it creates
Fixes https://github.com/k8snetworkplumbingwg/sriov-cni/issues/156
> Delete all cached data, /bin, /build and /test directories

- Makefile
Add missing help description
Fixes https://github.com/k8snetworkplumbingwg/sriov-cni/issues/155
> Fix make help description and logging info

- .github/workflows/buildtest.yml
Signed-off-by: Martin Kennelly <martin.kennelly@intel.com>
> Add build/test workflow for PR/push/cron

- .github/workflows/buildtest.yml
- Makefile
- README.md
- go.mod
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
> Bump golang 1.18 and k8s 1.24

- .github/workflows/buildtest.yml
- go.mod
Bump golang version to 1.20
Release notes: https://go.dev/doc/go1.20
Thanks
> bump golang version to 1.20

- Makefile
> Remove unused GODOC from Makefile

- .github/workflows/buildtest.yml
- .github/workflows/image-push-master.yml
- .github/workflows/image-push-release.yml
- .github/workflows/static-scan.yml
- Fix issue in pushing images to master/release with multi-arch build
- Bump action versions
> Workflow Maintenance

- .github/workflows/image-push-release.yml
> fix platform in image push release workflow

- .github/workflows/buildtest.yml
Add a Github Action lane to trigger the SRIOV Network Operator tests. This allows to verify if PR changes break any working scenario.
> Add SRIOV Operator CI lane

- .github/workflows/buildtest.yml
- .github/workflows/codeql.yml
- .github/workflows/static-scan.yml
align runners to use ubuntu-24.04
> chore: align runners
