sriov/sriov.go
Previously SRIOV-CNI works in below mode:
1. Given a PF info in conf file it will assign an available
VF with all required information in hand
Since DeviceId is now allocated by SRIOV device plugin and
exposed via APIServer by kubelet, this commit adds another
mode for SRIOV-CNI to work together with SRIOV device plugin:
2. It first trys to parse VF related DeviceId provided by meta
plugin, then derive other DeviceInfo such as Pfname, VfId etc
using this DeviceId. If all succeeds, it sets up the VF device
with derived DeviceInfo, if fails, it falls back to use mode 1.
=> Adding support with VF device information

sriov/sriov.go
This commit: 9d79c1da1af720d42ebced44fe28ec29aa4642af introduced
code which relies on DeviceInfo in NetConf. That DeviceInfo should
be provided by meta plugin, but multus from dev/k8s-deviceid-model
branch doesn't provide Deviceinfo.
Also probably SRIOV CNI plugin can be alone in future when kubernetes will
fully conform CNI specification.
Signed-off-by: Alexey Perevalov <a.perevalov@samsung.com>
=> Fix crash when DeviceInfo is absent

sriov/sriov.go
Shared VF links will be create during the VF setup procedure based
the number of devices found on '/sys/class/net/p3p1/device/virtfn4/net'
directory, and it will be renamed with the podIfName by adding a suffix
"d1". While releasing VFs, the check has to be corrected to see if there
are any shared VFs with "d1" suffix, before assumning Sharevf config.
Fixed the releaseVF, to ensure the Sharevf config is set correctly.
Fixes: https://github.com/intel/sriov-cni/issues/27
=> Sharedvf config should be set only when the shared link device is found

pkg/config/config.go
While adding test cases for config package, the new variable
nLink is left uninitialized, resulting in cni crash. Initialize
the var to the appropriate struct to allocate VF successfully.
=> Initalize nLink to allocate the VF

sriov/sriov.go
When using multus pluing the first interface will be eth0 and
the others will be netX. We need to make sure that before
we move VF which is eth0 to the container namespace it should
first be renamed to temp name before moving to the namespace.
This is to avoid conflict with the eth0 interface which already
exist in the namespace.
Fixes #40
=> Rename VF device name before moving to container namespace

Makefile
This fixes the issue #36 where build didn't invoke on file
modification.
Change-Id: Ieba7aa7b98896765521601bb8296e238406e6673
=> fix make to build on file updates

Dockerfile, images/entrypoint.sh
This patch changes Dockerfile to use multi-stage builds; specifically,
to use openshift builder and base images that already have golang,
make, git etc.; and to use 'make build' as part of the build process.
=> Fixed docker image build

README.md, pkg/config/config.go, pkg/config/config_test.go, pkg/types/types.go, sriov/main.go
Interface name is provided as args from the cni.
IF0NAME used in NetConf is not used and not required.
Signed-off-by: Saravanan KR <skramaja@redhat.com>
Fixes: #52
=> Remove IF0NAME from NetConf

README.md
A few typos were left in the README. I fixed them as I read through the document. I didn't touch any stylistic issues, just misspelled words.
=> Fix a few typos in README.md.

Dockerfile, Dockerfile.rhel7
This commit updates Dockerfile to use `alpine` instead of `openshift/origin-base` and adds Dockerfile.rhel7 for OpenShift build.
=> update Dockerfile and add Dockerfile.rhel7

pkg/utils/utils.go
this trivial change prevents cni from crashing if attempting to allocate a VF device that's already stood up in another pod
=> config mistake in spec can cause run-time out of range error

cmd/sriov/main.go, pkg/types/types.go
CNI RuntimeConfig takes preference if configured,
envArgs can still be used for Mac configuration if
meta plugin(Multus) passes Mac as envArgs.
Fixes #104
=> support CNI RuntimeConfig for Mac

README.md, pkg/sriov/sriov.go, pkg/sriov/sriov_test.go, pkg/types/types.go
Add support for configuring the min_tx_rate when
configured in the net-attach-def.
Note: min_tx_rate is only supported on Mellanox NICs.
For Intel NICs, do not configure min_tx_rate in the
net-attach-def, or, set the value to 0. Any other
config will cause the pod to fail to be created,
"Invalid Argument" in logs.
Signed-off-by: vpickard <vpickard@redhat.com>
=> Add support for min_tx_rate for SR-IOV VFs

pkg/sriov/sriov.go
Edited the format of the temp name to resolve #111 
Name format is now "temp_"+link index which is unique per node.
=> changed temp naming format

README.md, pkg/config/config.go, pkg/sriov/sriov.go, pkg/sriov/sriov_test.go, pkg/types/types.go
Restore original VF value when needed
This commit attempts to sort out (to some extent)
how a VF configuration is restored.
Until today, almost all VF configurations (except MAC)
where restored to some hardcoded value.
These values may not be desired by the system administrator
or may be invalid for some NIC driver implementation.
As an example, The behaviour of A VF where spoofchk is enabled
and admin mac address is zero is not well defined and is left
for the vendor driver implementors to define the behaviour.
This may cause the NIC's embedded switch to block traffic
from the VF, hence a POD will not be able to send traffic on that VF.
Today, when a user does not specify MAC and Spoofchk values in network
configuration will run into the issue described above when the VF is
reused for a …
=> Restore original VF state when needed

pkg/sriov/sriov.go
During static code analysis done with Go Vet it was discovered that
- pkg/sriov/sriov.go:151:13: result of fmt.Errorf call not used
Code within this pull request fixes above issue.
=> Fix unused call result

Dockerfile, Dockerfile.rhel7
During static code analysis done with HadoLint on DockerFiles several issues were discovered
- DL3003 Use WORKDIR to switch to a directory
- DL3018 Pin versions in apk add. Instead of apk add <package> use apk add <package>=<version>
- DL3019 Use the -no-cache switch to avoid the need to use -update and remove /var/cache/apk/* when done installing packages
- DL3006 Always tag the version of an image explicitly
- DL3020 Use COPY instead of ADD for files and folders
Code within this pull request fixes above issue.
=> Fix docker files after HadoLint check

images/entrypoint.sh
This PR fixes issues found by shellcheck in the bash script `entrypoint.sh`
- SC2006: Use $(..) instead of legacy ...
- SC2039: In POSIX sh, echo flags are not supported.
- SC2086: Double quote to prevent globbing and word splitting.
=> Fix shell script finding

pkg/sriov/sriov.go, pkg/sriov/sriov_test.go
According to CNI Convention MAC address returned in the Result is the
one configured by the plugin, but plugin return initial VF's MAC addr
even if it was passed in cni config.
MAC address value, returned by SetupVF function, assigned from the
linkObj after mac address was setted. That's not correct, since linkObj
don't point directly to underlying kernel's netlink object, so mac
address still has initial value.
Fix that by doing correct assignments.
Fix: #143
Signed-off-by: Dmytro Linkin <dlinkin@nvidia.com>
=> Fix wrong MAC address value in returned Result.

Makefile, README.md, cmd/sriov/main.go, go.mod, pkg/config/config.go, pkg/config/config_suite_test.go, pkg/sriov/sriov.go, pkg/sriov/sriov_suite_test.go, pkg/sriov/sriov_test.go
The code and documentation  was still pointing to Intel's
repos for both srio-network-device-plugin and srio-cni.
This patch changes to to NPWG's repos.
Signed-off-by: Maxime Coquelin <maxime.coquelin@redhat.com>
=> update repository with NPWG git repos URLs

README.md, cmd/sriov/main.go
For an external gateway pod that routes pod traffic to
external world via secondary dpdk interface, it requires
an IP address be allocated to the dpdk interface and exposed
in the multus network-status annotation.
This commit enables allocation of ipam IP address to dpdk
interface, but not configuring to the dpdk interface.
=> enable ip address allocation for dpdk interface

.travis.yml, Makefile, README.md
Files downloaded by 'go mod' are not writable (i.e: cannot be removed
with 'rm -r')
Fixes: #151 
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
=> Makefile: clean go mod cache

CONTRIBUTING.md
This commit adds a CONTRIBUTING document to
SRIOV CNI, it is similar to what is currenlty
present in SRIOV Network Device Plugin project.
The goal of this document is to provide an introduction
to newcomers on the process of creating issues and pull
requests as well as information on community meetings
where this project is discussed.
Signed-off-by: Adrian Chiris <adrianc@nvidia.com>
=> Add CONTRIBUTING doc to the project

cmd/sriov/main.go
SRIOV plugin needs to delegate the DEL action to the IPAM plugin to
release IPAM resources even for terminated containers without valid
network namespace path.
Signed-off-by: Yun Zhou <yunz@nvidia.com>
=> Release IPAM resources for exited containers

go.mod, go.sum, pkg/utils/utils.go
Use the govdpa library to inspect the device and determine if it's a
vdpa device and its driver.
If it's a vhost device, the CNI should not try to do any netdevice
configuration.
Fixes: #162 
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
=> Treat vhost-vdpa devices as DPDK devices

cmd/sriov/main.go
The current implementation only adds the MAC address to the response if the "ipam" field is non-empty.
Given than `ipam` is an optional field, this is not ideal.
Always add the MAC address to the response
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
=> Always add MAC address to response

go.mod, go.sum, pkg/utils/utils.go
This reverts commit 2080137b98a3f9d5bdb640a0ae47314483cd52fb.
As there is no hardware vendor that officially supports
VDPA over legacy SR-IOV devices, this code will not be used
(other than possible POCs).
Until we have hardware support, it should not be a
part of our mainline branch.
Signed-off-by: Adrian Chiris <adrianc@nvidia.com>
=> Revert "Treat vhost-vdpa devices as DPDK devices"

images/entrypoint.sh
Signed-off-by: Martin Kennelly <martin.kennelly@intel.com>
=> Allow daemonset to handle termination signals

images/k8s-v1.10-v1.15/sriov-cni-daemonset.yaml, images/k8s-v1.16/sriov-cni-daemonset.yaml
* Make fs read-only. Mounted volume not affected.
* Drop all linux caps
* Remove needless privileged permission
* Remove needless hostnetwork permission
Signed-off-by: Martin Kennelly <martin.kennelly@intel.com>
=> Improve daemonset security

README.md, pkg/sriov/sriov.go
It is more common that when no vlan tag is specified,
the interface will have no vlan at all.
The sriov-CNI acts differtly, and when a NAD is not configured with
vlan, the VF will keep it's old vlan tag. This behaviour
is not "natural" and could cause confusion.
This commit makes SRIOV-CNi treat no-valn as zero vlan,
which will effectively remove the vlan tag from the VF.
To prevent future misunderstandings a note is added tot the README
about the new behavior.
Signed-off-by: alonsadan <asadan@redhat.com>
=> set vlan to 0 if not defined.

.github/workflows/image-push-master.yml, .github/workflows/image-push-release.yml
With a push to master, a new image will be built and pushed to
github container registry at URL:
ghcr.io/k8snetworkplumbingwg/sriov-cni:${tag}
The accompanying tag can wither be sha or latest.
With a creation of a new release and associated tag which starts
with 'v', a new image will be built and pushed to github
container registry at URL:
ghcr.io/k8snetworkplumbingwg/sriov-cni:${tag}
The accompanying tag will start with 'v' and the version number.
Note:
I will remove WIP when Network Resources Injector's image push to GHCR is working ok. This is essentially the same patch.
Signed-off-by: Kennelly, Martin <martin.kennelly@intel.com>
=> create and push image to GHCR

go.mod, go.sum
With go 1.16, it no longer corrects missing deps
in go.sum. This patch fixes the go sum & mod files.
Signed-off-by: Martin Kennelly <martinkennelly@intel.com>
Executed "go mod tidy" on master with go 1.16.
=> Fix go 1.16 go mod build issue

.github/workflows/static-scan.yml
Add golangci-lint action with extra linters
besides the default set [1].
Add hadolint and shellcheck.
[1] https://golangci-lint.run/usage/linters
Signed-off-by: Martin Kennelly <martin.kennelly@intel.com>
=> Add static analysis workflow

pkg/utils/utils.go
VF index start from 0, totalVfs holds
the total number of VFs. loop should not
reach totalVFs value.
e.g in a system where a PF has 4 VFs
the corresponding VF indexes are: 0..3
Signed-off-by: Adrian Chiris <adrianc@nvidia.com>
=> Dont iterate on non existing VF ID

README.md, images/k8s-v1.16/sriov-cni-daemonset.yaml
This pull request updates deprecated label **beta.kubernetes.io/arch** to **kubernetes.io/arch** within example deployment file.
This label is deprecated since Kubernetes version 1.14 and is targeted for removal in v1.18
Fixes https://github.com/k8snetworkplumbingwg/sriov-cni/issues/193
=> Update documentation: label beta.kubernetes.io/arch to kubernetes.io/arch

images/k8s-v1.10-v1.15/sriov-cni-daemonset.yaml, images/k8s-v1.16/sriov-cni-daemonset.yaml
Update daemonset sriov-cni image to point to latest
We should always point to the latest image in master branch.
Signed-off-by: Adrian Chiris <adrianc@nvidia.com>
=> Update example daemonset images

.github/workflows/static-scan.yml, pkg/config/config_suite_test.go, pkg/sriov/sriov_suite_test.go, pkg/utils/testing.go, pkg/utils/utils_suite_test.go
Using Gomega assertions makes test errors more readable in most cases.
Signed-off-by: Andrea Panattoni <apanatto@redhat.com>
=> Avoid panicking in tests

.github/workflows/static-scan.yml, .golangci.yml, Makefile
This PR comes from [this thread on #205](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/205#discussion_r908494949)
`golint` has been deprecated and this PR replaces it with `golangci-lint`, in order to have the same lint output as CI.
Also, it replace `golint` sublinter with `revive`, as suggested by [golangci-lint in its output](https://github.com/k8snetworkplumbingwg/sriov-cni/runs/7095092180?check_suite_focus=true)
```
run golangci-lint
Running [/home/runner/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format=github-actions --enable=golint,bodyclose,gosec,whitespace] in [] ...
level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
```
=> lint: Switch to golangci-lint

.github/workflows/static-scan.yml, pkg/utils/testing.go, pkg/utils/utils.go
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
=> Fix golint issue

cmd/sriov/main.go, pkg/sriov/sriov.go, pkg/sriov/sriov_test.go
This PR fixes following issue:
#212
=> Reset the VF if failure occurs before the netconf is cached

cmd/sriov/main.go, pkg/sriov/sriov.go, pkg/utils/utils.go, pkg/utils/utils_test.go
The VF MAC address is, when requested, already set administratively via PF and works regardless whether VF trust is on or off.
Trying to set VF MAC address non-administratively without trust on is expected to gracefully fail. For example, here's the dmesg output example:
kernel: i40e 0000:3b:00.0: VF attempting to override administratively set MAC address, bring down and up the VF interface to resume normal operation
kernel: i40e 0000:3b:00.0: VF 0 failed opcode 10, retval: -1
kernel: iavf 0000:3b:02.0: Failed to add MAC filter, error IAVF_ERR_NVM
The same applies also when releasing the VF.
Tested on Intel XXV710 (i40e/iavf), Intel E810 (ice/iavf) and Mellanox ConnectX-4 (mlx5_core).
Signed-off-by: Carlos Goncalves <cgoncalves@redhat.com>
=> Do not try to set VF MAC non-administratively

.github/workflows/buildtest.yml, .github/workflows/image-push-master.yml, .github/workflows/image-push-release.yml, Dockerfile.arm64, Dockerfile.ppc64le, images/entrypoint.sh
support build image for arm64 and ppc64le
ATM, `sriov-cni` only for amd64, This PR supports building images for both `arm64` and `ppc64le` architectures in the workflow file for building images.
Signed-off-by: cyclinder <qifeng.guo@daocloud.io>
=> support build image for arm64 and ppc64le

pkg/utils/utils.go
Signed-off-by: yanggang <gang.yang@daocloud.io>
/kind cleanup
```
for _, invalidMACAddress := range invalidMACAddresses {
if bytes.Equal(addr, invalidMACAddress) {
valid = false
break
}
}
```
the code will reduce the loop cost , when it is first found to be false . just break and skip next process.
And 
```
if err != nil || linkObj.Attrs() == nil {
return fmt.Errorf("failed to get netlink device with name %q: %v", ifName, err)
}
```
will fix the potential panic, when linkObj.Attrs() is nil..
=> code clean for pkg/utils.go IsValidMACAddress

Makefile
make didn't work without it. Please keep golangci-lint version consistent in .github/workflows/static-scan.yml and in Makefile
=> Bump golangci-lint in Makefile as well

.github/workflows/buildtest.yml
This pull request enables race detection in unit tests by modifying the Go test step in buildtest.yml. The test configuration is updated to include the '-race' flag, allowing thorough race detection during testing. 
Race detection can help identifying potential data race conditions, which can lead to hard-to-debug issues in concurrent code. By enabling race detection in our unit tests, we can detect and address these race conditions, ensuring the reliability and stability of our code. (for further reference view: https://go.dev/doc/articles/race_detector)
=> Enable race detection in unit tests

pkg/sriov/sriov.go, pkg/types/types.go
now netlink support getting the trust info from the vf so we can remove the TODO :)
=> Add support to revert VF trust

pkg/sriov/sriov.go, pkg/sriov/sriov_suite_test.go, pkg/sriov/sriov_test.go, pkg/utils/testing.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This commit add a retry function for all the mac address allocation functions.
this is needed because some of the drivers have async mac allocation or get a device or resouce busy errors until the vf device is fully configured on the system so instead of failing the CNI we just wait 100 miliseconds
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
=> Add both hardware and nic mac allocation retry

cmd/sriov/main.go, pkg/config/config.go, pkg/config/config_test.go, pkg/sriov/sriov.go, pkg/sriov/sriov_test.go, pkg/types/types.go
this commit passes the mac address in the cni result.
this will also work in case the vf uses a user-space driver like vfio as we have the mac address for it from the PF
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
=> expose mac address as part of networks-status in pod yaml

cmd/sriov/main.go
Before this fix there was a problem with upper or lower case mac address
=> Fix mac address verification

pkg/config/config.go, pkg/sriov/sriov.go, pkg/sriov/sriov_test.go, pkg/types/types.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This parameter is only used in a check that is not valid because only a single interface name is used by the plugin. Additionally, the func GetVFLinkNames was renamed to GetVFLinkName to reflect that a single name is returned.
=> Delete ConfIFNames parameter

cmd/sriov/main.go
This checks if the VF is still present in the node when the Del command is executed.
Fixes #271
=> Check VF ID existence in Del cmd

pkg/config/config.go, pkg/config/config_test.go
- Add check to not allow non default values of qos and proto when vlan is zero.
- Remove check when vlan is zero and qos and proto are not in config since default values are now set.
=> Fix checks for vlan parameters

Makefile, cmd/sriov/main.go, docs/configuration-reference.md, go.mod, go.sum, pkg/config/config.go, pkg/logging/logging.go, pkg/logging/logging_suite_test.go, pkg/logging/logging_test.go, pkg/sriov/sriov.go, pkg/types/types.go, pkg/utils/pci_allocator.go
Adds both configurable debug logging to stderr and optionally to
file as well as error logging for issue 275.
Reported-at: https://github.com/k8snetworkplumbingwg/sriov-cni/issues/275
Signed-off-by: Andreas Karis <ak.karis@gmail.com>
=> Add logging to sriov-cni

pkg/sriov/sriov.go, pkg/sriov/sriov_test.go
Setting the MAC address at the end of SetupVF reduces the chances of race conditions with tools that set MAC i address asynchronously (i.e. iavf).
=> Set MAC address after renaming the interface

.github/workflows/image-push-release.yml
- remove "latest" image tage from docker meta
- remove use of IMAGE_NAME in manifest creation as docker meta tag is the full image name
=> Fix release workflow

Makefile, images/entrypoint.sh, images/image_test.sh
Container image might be used as `initcontainers` in kubernetes Pods. In such scenarios, it's important for the image entrypoint to exits once the copy logic is completed. Otherwise, the pod would stuck in a `PodInitializing` phase.
Add Makefile rule `image-test` to check the integrity of the entrypoint.sh script.
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
refs:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/581
=> Optionally avoid sleeping in `entrypoint.sh`

.gitignore, OWNERS
Add an OWNERS file to the SR-IOV CNI project. This OWNERS file will be reflected into the github permissions for this project once merged.
This proposed OWNERS file comes from discussion around the way the NPWG handles project roles which took place in recent community meetings.
A governance doc defining project roles and process is pending approval at  https://github.com/k8snetworkplumbingwg/community/pull/23 This change was discussed in the NPWG community meetings on [Feb. 8th](https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit#heading=h.3hj4tertx9nj) and [Feb 22nd](https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit#heading=h.5cn4jef8loy1). 
Currently SR-IOV CNI has the following owners:
```
hustcat read
zeeke maintain …
```
=> chore: Add OWNERS file

pkg/config/config.go, pkg/sriov/sriov.go, pkg/sriov/sriov_test.go
Fixes https://github.com/k8snetworkplumbingwg/sriov-cni/issues/291
=> Skip setting vlan when parameter is not present

pkg/config/config_test.go, pkg/sriov/sriov_test.go, pkg/types/types.go, pkg/utils/utils.go, pkg/utils/utils_test.go
before we send a pointer to the netConf object so the marshal function didn't parse all the information needed
=> Fix the cache save

images/sriov-cni-daemonset.yaml
- Add control-plane toleration
- remove nodeSelector for amd64 arch as we have multi-arch images
- rename ds - remove amd64 suffix
=> Update daemonset yaml

cmd/sriov/main.go, pkg/utils/netlink_manager.go, pkg/utils/packet.go, pkg/utils/packet_test.go
This is a follow up to c241dcb4367c.
what happens is that after sriov-cni sets up the interface, initially the interface does not have carrier. Sent GARP/IPv6 NA at that point are lost.
Instead, wait a bit until the interface has carrier.
See-also: https://issues.redhat.com/browse/OCPBUGS-30549
=> Wait for carrier before announcing IPs via GARP/NA

docs/configuration-reference.md
Taking a look of the example, looks like the code block is referring to an old name of the plugin.
Even in the doc file, in line 8 appears the correct type: 
* `type` (string, required): "sriov"
=> Update configuration-reference.md in SRIOV DPDK config

cmd/sriov/main.go
In the case where the Gratuitous ARPs send function failed we failed the all CNI create and revert the configuration
=> Fix Gratuitous ARPs critical error on ipv6

.github/workflows/buildtest.yml, Makefile, go.mod
- cleanup makefile
- update buildtest workflow
- ran go mod tidy, update go.mod
=> Makefile refactor

go.mod, go.sum
this commit bump netlink to support a new variable len validation in the kernel for vf vlan protocol
Closes https://github.com/k8snetworkplumbingwg/sriov-cni/issues/303
=> Bump netlink to fix SizeofVfVlanInfo

Makefile
The unit tests require CAP_NET_ADMIN permissions, so commonly they fail in a developer environment for valid reasons.
Having the "test" target part of the default make target ("all") will fail in such an environment, which is inconvenient.
Running unit tests should be a separate make target. To run tests, explicitly run `make test`.
Fixes: f2dbb73a9938 ('Makefile refactor')
---
Follow-up to https://github.com/k8snetworkplumbingwg/sriov-cni/pull/305#issuecomment-2259950853
=> Makefile: dont't run "test" as part of default "all" make target

pkg/sriov/mocks/pci_utils_mock.go, pkg/sriov/sriov.go, pkg/sriov/sriov_test.go, pkg/utils/packet.go, pkg/utils/utils.go
When kernel initially adds an IPv6 address, it is still tentative and
pending DuplicateAddressDetection. Trying to use the address results in
EADDRNOTAVAIL error.
Detect that error, and retry for up to 3 seconds to send the message.
Unfortunately, DAD can easily take more than a second, so this change
delays the completion of the CNI binary quite a bit.
---
@SchSeba  Follow-up for https://github.com/k8snetworkplumbingwg/sriov-cni/pull/306
This seems to happen with Openshift 4.17, which makes me wonder whether previous versions had ~opportunistic~optimistic DAD enabled. If so, why was it disabled?
=> Retry Sendto() for IPv6 NA for tentative IPv6 addresses and EADDRNOTAVAIL

pkg/sriov/sriov.go, pkg/sriov/sriov_test.go, pkg/types/types.go, pkg/utils/mocks/netlink_manager_mock.go, pkg/utils/netlink_manager.go
we introduce this feature in the cni to handle cases where a pod that used the vf has net_admin and change the MTU
on the VF.
when that pod is removed the VF will go back to the host and be available
for a new pod to run but when that VF gets allocated to the pod it will
remain with an unexpected MTU.
=> Revert mtu

.github/workflows/buildtest.yml, cmd/sriov/main.go, pkg/config/config.go, pkg/config/config_test.go, pkg/utils/pci_allocator.go
The VF might have been assigned to another running
Pod if the network namespace is not present. In cases
like this, resetting the VF might break the configuration
of the running Pod.
The above scenario might occur when the IPAM plugin takes a lot of time to complete, and the CmdDel gets called
multiple times.
Check if the namespace is still present before resetting the VF
@bn222 @SchSeba WDYT about this approach?
=> Avoid resetting the VF if the netns does not exist 

.github/workflows/buildtest.yml, .github/workflows/static-scan.yml, Makefile, pkg/utils/testing.go, test/integration/libtest.sh, test/integration/test_concurrent.sh, test/integration/test_sriov_cni.sh, test/integration/tmp/.gitignore
Integration tests for
- https://github.com/k8snetworkplumbingwg/sriov-cni/pull/313
- https://github.com/k8snetworkplumbingwg/sriov-cni/pull/316
Add integration test code coverage
=> Lock file integration test
